"""
Tests for backend.file_processor — file reading, base64 encoding, error handling.
"""
import pytest
import base64
import io

from backend.file_processor import process_file


class TestPDFProcessing:
    def test_valid_pdf_text_extraction(self):
        """Create a minimal valid PDF and check text extraction."""
        # PyPDF2 can read PDFs generated by reportlab or similar,
        # but let's use a real minimal PDF binary.
        # We'll test with a malformed one to ensure error path works.
        result = process_file(b"not a pdf", "test.pdf")
        assert result["file_type"] == "pdf"
        # Should return an error message, not crash
        assert result["text"] is not None
        assert "Error reading PDF" in result["text"]

    def test_empty_pdf(self):
        result = process_file(b"", "empty.pdf")
        assert result["file_type"] == "pdf"
        assert result["text"] is not None  # Should have error message


class TestImageProcessing:
    def test_png_base64_encoding(self):
        fake_image = b"\x89PNG\r\n\x1a\n" + b"\x00" * 100
        result = process_file(fake_image, "invoice.png")
        assert result["file_type"] == "png"
        assert result["image_base64"] is not None
        # Verify it's valid base64
        decoded = base64.b64decode(result["image_base64"])
        assert decoded == fake_image

    def test_jpg_base64_encoding(self):
        fake_image = b"\xff\xd8\xff" + b"\x00" * 50
        result = process_file(fake_image, "photo.jpg")
        assert result["file_type"] == "jpg"
        assert result["image_base64"] is not None

    def test_jpeg_extension(self):
        result = process_file(b"\xff\xd8\xff", "photo.jpeg")
        assert result["file_type"] == "jpeg"
        assert result["image_base64"] is not None

    def test_image_has_no_text(self):
        result = process_file(b"\x89PNG", "img.png")
        assert result["text"] is None


class TestTextAndCSV:
    def test_txt_file(self):
        content = "Invoice #123\nTotal: $500"
        result = process_file(content.encode("utf-8"), "invoice.txt")
        assert result["file_type"] == "txt"
        assert result["text"] == content

    def test_csv_file(self):
        content = "item,qty,price\nWidget,10,5.00"
        result = process_file(content.encode("utf-8"), "data.csv")
        assert result["file_type"] == "csv"
        assert "Widget" in result["text"]

    def test_latin1_fallback(self):
        """Non-UTF-8 bytes should fall back to latin-1."""
        content = bytes([0xC0, 0xC1, 0xFE, 0xFF])  # Invalid UTF-8
        result = process_file(content, "weird.txt")
        assert result["text"] is not None  # Should not crash


class TestDocx:
    def test_malformed_docx(self):
        result = process_file(b"not a docx", "test.docx")
        assert result["file_type"] == "docx"
        assert "Error reading DOCX" in result["text"]


class TestUnsupportedFiles:
    def test_unknown_extension(self):
        result = process_file(b"data", "file.xyz")
        assert result["file_type"] == "xyz"
        assert "Unsupported file type" in result["text"]

    def test_no_extension(self):
        result = process_file(b"data", "noext")
        assert result["file_type"] == ""
        # Empty extension falls through to the else branch
        assert "Unsupported" in result["text"]


class TestEdgeCases:
    def test_filename_with_multiple_dots(self):
        result = process_file(b"hello", "my.invoice.2024.txt")
        assert result["file_type"] == "txt"
        assert result["text"] == "hello"

    def test_uppercase_extension(self):
        """Bug check: extension should be lowercased."""
        result = process_file(b"hello", "INVOICE.TXT")
        assert result["file_type"] == "txt"
        assert result["text"] == "hello"

    def test_return_structure(self):
        """Ensure all results always have the three expected keys."""
        result = process_file(b"data", "test.txt")
        assert "text" in result
        assert "image_base64" in result
        assert "file_type" in result
